namespace HELVETAS
{
    partial class settibg_db
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(settibg_db));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuAppBar1 = new Bunifu.Utils.BunifuAppBar();
            this.connect_but = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.save_but = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.test_connect_but = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txt_password = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_name_db = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_server = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.disconnect_but = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(41, 182);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(70, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Name_server";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(41, 231);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(85, 13);
            this.label2.TabIndex = 3;
            this.label2.Text = "Name_database";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(41, 280);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(61, 13);
            this.label3.TabIndex = 5;
            this.label3.Text = "Name_user";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(41, 328);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(53, 13);
            this.label4.TabIndex = 7;
            this.label4.Text = "Password";
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = false;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = false;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = false;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = false;
            this.bunifuFormDock1.DockingOptions.DockLeft = false;
            this.bunifuFormDock1.DockingOptions.DockRight = false;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = false;
            this.bunifuFormDock1.DockingOptions.DockTopRight = false;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = false;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuAppBar1
            // 
            this.bunifuAppBar1.BackColor = System.Drawing.Color.RoyalBlue;
            this.bunifuAppBar1.ControlBoxColor = System.Drawing.Color.White;
            this.bunifuAppBar1.ControlBoxColorActive = System.Drawing.Color.White;
            this.bunifuAppBar1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuAppBar1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuAppBar1.ForeColor = System.Drawing.Color.White;
            this.bunifuAppBar1.Icon = null;
            this.bunifuAppBar1.Location = new System.Drawing.Point(0, 0);
            this.bunifuAppBar1.Name = "bunifuAppBar1";
            this.bunifuAppBar1.Size = new System.Drawing.Size(450, 34);
            this.bunifuAppBar1.TabIndex = 15;
            this.bunifuAppBar1.Title = "";
            this.bunifuAppBar1.TitleMargin = new System.Windows.Forms.Padding(47, 12, 0, 0);
            // 
            // connect_but
            // 
            this.connect_but.AllowAnimations = true;
            this.connect_but.AllowMouseEffects = true;
            this.connect_but.AllowToggling = false;
            this.connect_but.AnimationSpeed = 200;
            this.connect_but.AutoGenerateColors = false;
            this.connect_but.AutoRoundBorders = false;
            this.connect_but.AutoSizeLeftIcon = true;
            this.connect_but.AutoSizeRightIcon = true;
            this.connect_but.BackColor = System.Drawing.Color.Transparent;
            this.connect_but.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.connect_but.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("connect_but.BackgroundImage")));
            this.connect_but.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.connect_but.ButtonText = "connect";
            this.connect_but.ButtonTextMarginLeft = 0;
            this.connect_but.ColorContrastOnClick = 45;
            this.connect_but.ColorContrastOnHover = 45;
            this.connect_but.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.connect_but.CustomizableEdges = borderEdges7;
            this.connect_but.DialogResult = System.Windows.Forms.DialogResult.None;
            this.connect_but.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.connect_but.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.connect_but.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.connect_but.Enabled = false;
            this.connect_but.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.connect_but.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.connect_but.ForeColor = System.Drawing.Color.White;
            this.connect_but.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.connect_but.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.connect_but.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.connect_but.IconMarginLeft = 11;
            this.connect_but.IconPadding = 10;
            this.connect_but.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.connect_but.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.connect_but.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.connect_but.IconSize = 25;
            this.connect_but.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.connect_but.IdleBorderRadius = 20;
            this.connect_but.IdleBorderThickness = 1;
            this.connect_but.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.connect_but.IdleIconLeftImage = null;
            this.connect_but.IdleIconRightImage = null;
            this.connect_but.IndicateFocus = false;
            this.connect_but.Location = new System.Drawing.Point(165, 391);
            this.connect_but.Name = "connect_but";
            this.connect_but.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.connect_but.OnDisabledState.BorderRadius = 20;
            this.connect_but.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.connect_but.OnDisabledState.BorderThickness = 1;
            this.connect_but.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.connect_but.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.connect_but.OnDisabledState.IconLeftImage = null;
            this.connect_but.OnDisabledState.IconRightImage = null;
            this.connect_but.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.connect_but.onHoverState.BorderRadius = 20;
            this.connect_but.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.connect_but.onHoverState.BorderThickness = 1;
            this.connect_but.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.connect_but.onHoverState.ForeColor = System.Drawing.Color.White;
            this.connect_but.onHoverState.IconLeftImage = null;
            this.connect_but.onHoverState.IconRightImage = null;
            this.connect_but.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.connect_but.OnIdleState.BorderRadius = 20;
            this.connect_but.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.connect_but.OnIdleState.BorderThickness = 1;
            this.connect_but.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.connect_but.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.connect_but.OnIdleState.IconLeftImage = null;
            this.connect_but.OnIdleState.IconRightImage = null;
            this.connect_but.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.connect_but.OnPressedState.BorderRadius = 20;
            this.connect_but.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.connect_but.OnPressedState.BorderThickness = 1;
            this.connect_but.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.connect_but.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.connect_but.OnPressedState.IconLeftImage = null;
            this.connect_but.OnPressedState.IconRightImage = null;
            this.connect_but.Size = new System.Drawing.Size(125, 25);
            this.connect_but.TabIndex = 14;
            this.connect_but.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.connect_but.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.connect_but.TextMarginLeft = 0;
            this.connect_but.TextPadding = new System.Windows.Forms.Padding(0);
            this.connect_but.UseDefaultRadiusAndThickness = true;
            this.connect_but.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // bunifuButton24
            // 
            this.bunifuButton24.AllowAnimations = true;
            this.bunifuButton24.AllowMouseEffects = true;
            this.bunifuButton24.AllowToggling = false;
            this.bunifuButton24.AnimationSpeed = 200;
            this.bunifuButton24.AutoGenerateColors = false;
            this.bunifuButton24.AutoRoundBorders = false;
            this.bunifuButton24.AutoSizeLeftIcon = true;
            this.bunifuButton24.AutoSizeRightIcon = true;
            this.bunifuButton24.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton24.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.bunifuButton24.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton24.BackgroundImage")));
            this.bunifuButton24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.ButtonText = "выход";
            this.bunifuButton24.ButtonTextMarginLeft = 0;
            this.bunifuButton24.ColorContrastOnClick = 45;
            this.bunifuButton24.ColorContrastOnHover = 45;
            this.bunifuButton24.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton24.CustomizableEdges = borderEdges8;
            this.bunifuButton24.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton24.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton24.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton24.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton24.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton24.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton24.ForeColor = System.Drawing.Color.White;
            this.bunifuButton24.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton24.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton24.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton24.IconMarginLeft = 11;
            this.bunifuButton24.IconPadding = 10;
            this.bunifuButton24.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton24.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton24.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton24.IconSize = 25;
            this.bunifuButton24.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.bunifuButton24.IdleBorderRadius = 10;
            this.bunifuButton24.IdleBorderThickness = 1;
            this.bunifuButton24.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.bunifuButton24.IdleIconLeftImage = null;
            this.bunifuButton24.IdleIconRightImage = null;
            this.bunifuButton24.IndicateFocus = false;
            this.bunifuButton24.Location = new System.Drawing.Point(163, 466);
            this.bunifuButton24.Name = "bunifuButton24";
            this.bunifuButton24.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton24.OnDisabledState.BorderRadius = 10;
            this.bunifuButton24.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.OnDisabledState.BorderThickness = 1;
            this.bunifuButton24.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton24.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton24.OnDisabledState.IconLeftImage = null;
            this.bunifuButton24.OnDisabledState.IconRightImage = null;
            this.bunifuButton24.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton24.onHoverState.BorderRadius = 10;
            this.bunifuButton24.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.onHoverState.BorderThickness = 1;
            this.bunifuButton24.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton24.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton24.onHoverState.IconLeftImage = null;
            this.bunifuButton24.onHoverState.IconRightImage = null;
            this.bunifuButton24.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.bunifuButton24.OnIdleState.BorderRadius = 10;
            this.bunifuButton24.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.OnIdleState.BorderThickness = 1;
            this.bunifuButton24.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.bunifuButton24.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton24.OnIdleState.IconLeftImage = null;
            this.bunifuButton24.OnIdleState.IconRightImage = null;
            this.bunifuButton24.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton24.OnPressedState.BorderRadius = 10;
            this.bunifuButton24.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.OnPressedState.BorderThickness = 1;
            this.bunifuButton24.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton24.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton24.OnPressedState.IconLeftImage = null;
            this.bunifuButton24.OnPressedState.IconRightImage = null;
            this.bunifuButton24.Size = new System.Drawing.Size(133, 25);
            this.bunifuButton24.TabIndex = 12;
            this.bunifuButton24.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton24.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton24.TextMarginLeft = 0;
            this.bunifuButton24.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton24.UseDefaultRadiusAndThickness = true;
            this.bunifuButton24.Click += new System.EventHandler(this.bunifuButton24_Click);
            // 
            // save_but
            // 
            this.save_but.AllowAnimations = true;
            this.save_but.AllowMouseEffects = true;
            this.save_but.AllowToggling = false;
            this.save_but.AnimationSpeed = 200;
            this.save_but.AutoGenerateColors = false;
            this.save_but.AutoRoundBorders = false;
            this.save_but.AutoSizeLeftIcon = true;
            this.save_but.AutoSizeRightIcon = true;
            this.save_but.BackColor = System.Drawing.Color.Transparent;
            this.save_but.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.save_but.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("save_but.BackgroundImage")));
            this.save_but.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save_but.ButtonText = "save";
            this.save_but.ButtonTextMarginLeft = 0;
            this.save_but.ColorContrastOnClick = 45;
            this.save_but.ColorContrastOnHover = 45;
            this.save_but.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.save_but.CustomizableEdges = borderEdges9;
            this.save_but.DialogResult = System.Windows.Forms.DialogResult.None;
            this.save_but.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.save_but.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.save_but.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.save_but.Enabled = false;
            this.save_but.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.save_but.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.save_but.ForeColor = System.Drawing.Color.White;
            this.save_but.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.save_but.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.save_but.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.save_but.IconMarginLeft = 11;
            this.save_but.IconPadding = 10;
            this.save_but.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.save_but.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.save_but.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.save_but.IconSize = 25;
            this.save_but.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.save_but.IdleBorderRadius = 10;
            this.save_but.IdleBorderThickness = 1;
            this.save_but.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.save_but.IdleIconLeftImage = null;
            this.save_but.IdleIconRightImage = null;
            this.save_but.IndicateFocus = false;
            this.save_but.Location = new System.Drawing.Point(301, 466);
            this.save_but.Name = "save_but";
            this.save_but.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.save_but.OnDisabledState.BorderRadius = 10;
            this.save_but.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save_but.OnDisabledState.BorderThickness = 1;
            this.save_but.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.save_but.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.save_but.OnDisabledState.IconLeftImage = null;
            this.save_but.OnDisabledState.IconRightImage = null;
            this.save_but.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.save_but.onHoverState.BorderRadius = 10;
            this.save_but.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save_but.onHoverState.BorderThickness = 1;
            this.save_but.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.save_but.onHoverState.ForeColor = System.Drawing.Color.White;
            this.save_but.onHoverState.IconLeftImage = null;
            this.save_but.onHoverState.IconRightImage = null;
            this.save_but.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.save_but.OnIdleState.BorderRadius = 10;
            this.save_but.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save_but.OnIdleState.BorderThickness = 1;
            this.save_but.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(67)))), ((int)(((byte)(109)))));
            this.save_but.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.save_but.OnIdleState.IconLeftImage = null;
            this.save_but.OnIdleState.IconRightImage = null;
            this.save_but.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.save_but.OnPressedState.BorderRadius = 10;
            this.save_but.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save_but.OnPressedState.BorderThickness = 1;
            this.save_but.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.save_but.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.save_but.OnPressedState.IconLeftImage = null;
            this.save_but.OnPressedState.IconRightImage = null;
            this.save_but.Size = new System.Drawing.Size(133, 25);
            this.save_but.TabIndex = 11;
            this.save_but.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.save_but.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.save_but.TextMarginLeft = 0;
            this.save_but.TextPadding = new System.Windows.Forms.Padding(0);
            this.save_but.UseDefaultRadiusAndThickness = true;
            this.save_but.Click += new System.EventHandler(this.save_but_Click);
            // 
            // test_connect_but
            // 
            this.test_connect_but.AllowAnimations = true;
            this.test_connect_but.AllowMouseEffects = true;
            this.test_connect_but.AllowToggling = false;
            this.test_connect_but.AnimationSpeed = 200;
            this.test_connect_but.AutoGenerateColors = false;
            this.test_connect_but.AutoRoundBorders = false;
            this.test_connect_but.AutoSizeLeftIcon = true;
            this.test_connect_but.AutoSizeRightIcon = true;
            this.test_connect_but.BackColor = System.Drawing.Color.Transparent;
            this.test_connect_but.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.test_connect_but.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("test_connect_but.BackgroundImage")));
            this.test_connect_but.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.test_connect_but.ButtonText = "test_connect";
            this.test_connect_but.ButtonTextMarginLeft = 0;
            this.test_connect_but.ColorContrastOnClick = 45;
            this.test_connect_but.ColorContrastOnHover = 45;
            this.test_connect_but.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.test_connect_but.CustomizableEdges = borderEdges10;
            this.test_connect_but.DialogResult = System.Windows.Forms.DialogResult.None;
            this.test_connect_but.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.test_connect_but.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.test_connect_but.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.test_connect_but.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.test_connect_but.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.test_connect_but.ForeColor = System.Drawing.Color.White;
            this.test_connect_but.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.test_connect_but.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.test_connect_but.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.test_connect_but.IconMarginLeft = 11;
            this.test_connect_but.IconPadding = 10;
            this.test_connect_but.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.test_connect_but.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.test_connect_but.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.test_connect_but.IconSize = 25;
            this.test_connect_but.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.test_connect_but.IdleBorderRadius = 20;
            this.test_connect_but.IdleBorderThickness = 1;
            this.test_connect_but.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.test_connect_but.IdleIconLeftImage = null;
            this.test_connect_but.IdleIconRightImage = null;
            this.test_connect_but.IndicateFocus = false;
            this.test_connect_but.Location = new System.Drawing.Point(34, 391);
            this.test_connect_but.Name = "test_connect_but";
            this.test_connect_but.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.test_connect_but.OnDisabledState.BorderRadius = 20;
            this.test_connect_but.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.test_connect_but.OnDisabledState.BorderThickness = 1;
            this.test_connect_but.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.test_connect_but.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.test_connect_but.OnDisabledState.IconLeftImage = null;
            this.test_connect_but.OnDisabledState.IconRightImage = null;
            this.test_connect_but.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.test_connect_but.onHoverState.BorderRadius = 20;
            this.test_connect_but.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.test_connect_but.onHoverState.BorderThickness = 1;
            this.test_connect_but.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.test_connect_but.onHoverState.ForeColor = System.Drawing.Color.White;
            this.test_connect_but.onHoverState.IconLeftImage = null;
            this.test_connect_but.onHoverState.IconRightImage = null;
            this.test_connect_but.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.test_connect_but.OnIdleState.BorderRadius = 20;
            this.test_connect_but.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.test_connect_but.OnIdleState.BorderThickness = 1;
            this.test_connect_but.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.test_connect_but.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.test_connect_but.OnIdleState.IconLeftImage = null;
            this.test_connect_but.OnIdleState.IconRightImage = null;
            this.test_connect_but.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.test_connect_but.OnPressedState.BorderRadius = 20;
            this.test_connect_but.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.test_connect_but.OnPressedState.BorderThickness = 1;
            this.test_connect_but.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.test_connect_but.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.test_connect_but.OnPressedState.IconLeftImage = null;
            this.test_connect_but.OnPressedState.IconRightImage = null;
            this.test_connect_but.Size = new System.Drawing.Size(125, 25);
            this.test_connect_but.TabIndex = 10;
            this.test_connect_but.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.test_connect_but.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.test_connect_but.TextMarginLeft = 0;
            this.test_connect_but.TextPadding = new System.Windows.Forms.Padding(0);
            this.test_connect_but.UseDefaultRadiusAndThickness = true;
            this.test_connect_but.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // txt_password
            // 
            this.txt_password.AcceptsReturn = false;
            this.txt_password.AcceptsTab = false;
            this.txt_password.AnimationSpeed = 200;
            this.txt_password.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_password.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_password.AutoSizeHeight = true;
            this.txt_password.BackColor = System.Drawing.Color.Transparent;
            this.txt_password.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_password.BackgroundImage")));
            this.txt_password.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_password.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_password.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_password.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_password.BorderRadius = 10;
            this.txt_password.BorderThickness = 1;
            this.txt_password.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_password.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_password.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_password.DefaultText = "";
            this.txt_password.FillColor = System.Drawing.Color.White;
            this.txt_password.HideSelection = true;
            this.txt_password.IconLeft = null;
            this.txt_password.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_password.IconPadding = 10;
            this.txt_password.IconRight = null;
            this.txt_password.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_password.Lines = new string[0];
            this.txt_password.Location = new System.Drawing.Point(34, 344);
            this.txt_password.MaxLength = 32767;
            this.txt_password.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_password.Modified = false;
            this.txt_password.Multiline = false;
            this.txt_password.Name = "txt_password";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_password.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_password.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_password.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_password.OnIdleState = stateProperties20;
            this.txt_password.Padding = new System.Windows.Forms.Padding(3);
            this.txt_password.PasswordChar = '\0';
            this.txt_password.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_password.PlaceholderText = "password";
            this.txt_password.ReadOnly = false;
            this.txt_password.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_password.SelectedText = "";
            this.txt_password.SelectionLength = 0;
            this.txt_password.SelectionStart = 0;
            this.txt_password.ShortcutsEnabled = true;
            this.txt_password.Size = new System.Drawing.Size(379, 30);
            this.txt_password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_password.TabIndex = 8;
            this.txt_password.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_password.TextMarginBottom = 0;
            this.txt_password.TextMarginLeft = 3;
            this.txt_password.TextMarginTop = 1;
            this.txt_password.TextPlaceholder = "password";
            this.txt_password.UseSystemPasswordChar = false;
            this.txt_password.WordWrap = true;
            // 
            // txt_user
            // 
            this.txt_user.AcceptsReturn = false;
            this.txt_user.AcceptsTab = false;
            this.txt_user.AnimationSpeed = 200;
            this.txt_user.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user.AutoSizeHeight = true;
            this.txt_user.BackColor = System.Drawing.Color.Transparent;
            this.txt_user.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user.BackgroundImage")));
            this.txt_user.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_user.BorderRadius = 10;
            this.txt_user.BorderThickness = 1;
            this.txt_user.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_user.DefaultText = "";
            this.txt_user.FillColor = System.Drawing.Color.White;
            this.txt_user.HideSelection = true;
            this.txt_user.IconLeft = null;
            this.txt_user.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user.IconPadding = 10;
            this.txt_user.IconRight = null;
            this.txt_user.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user.Lines = new string[0];
            this.txt_user.Location = new System.Drawing.Point(34, 296);
            this.txt_user.MaxLength = 32767;
            this.txt_user.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user.Modified = false;
            this.txt_user.Multiline = false;
            this.txt_user.Name = "txt_user";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user.OnIdleState = stateProperties24;
            this.txt_user.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user.PasswordChar = '\0';
            this.txt_user.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_user.PlaceholderText = "user";
            this.txt_user.ReadOnly = false;
            this.txt_user.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user.SelectedText = "";
            this.txt_user.SelectionLength = 0;
            this.txt_user.SelectionStart = 0;
            this.txt_user.ShortcutsEnabled = true;
            this.txt_user.Size = new System.Drawing.Size(379, 30);
            this.txt_user.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user.TabIndex = 6;
            this.txt_user.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user.TextMarginBottom = 0;
            this.txt_user.TextMarginLeft = 3;
            this.txt_user.TextMarginTop = 1;
            this.txt_user.TextPlaceholder = "user";
            this.txt_user.UseSystemPasswordChar = false;
            this.txt_user.WordWrap = true;
            // 
            // txt_name_db
            // 
            this.txt_name_db.AcceptsReturn = false;
            this.txt_name_db.AcceptsTab = false;
            this.txt_name_db.AnimationSpeed = 200;
            this.txt_name_db.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_name_db.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_name_db.AutoSizeHeight = true;
            this.txt_name_db.BackColor = System.Drawing.Color.Transparent;
            this.txt_name_db.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_name_db.BackgroundImage")));
            this.txt_name_db.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_name_db.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_name_db.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_name_db.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_name_db.BorderRadius = 10;
            this.txt_name_db.BorderThickness = 1;
            this.txt_name_db.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_name_db.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_name_db.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_name_db.DefaultText = "";
            this.txt_name_db.FillColor = System.Drawing.Color.White;
            this.txt_name_db.HideSelection = true;
            this.txt_name_db.IconLeft = null;
            this.txt_name_db.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_name_db.IconPadding = 10;
            this.txt_name_db.IconRight = null;
            this.txt_name_db.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_name_db.Lines = new string[0];
            this.txt_name_db.Location = new System.Drawing.Point(34, 247);
            this.txt_name_db.MaxLength = 32767;
            this.txt_name_db.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_name_db.Modified = false;
            this.txt_name_db.Multiline = false;
            this.txt_name_db.Name = "txt_name_db";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_name_db.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_name_db.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_name_db.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_name_db.OnIdleState = stateProperties28;
            this.txt_name_db.Padding = new System.Windows.Forms.Padding(3);
            this.txt_name_db.PasswordChar = '\0';
            this.txt_name_db.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_name_db.PlaceholderText = "database";
            this.txt_name_db.ReadOnly = false;
            this.txt_name_db.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_name_db.SelectedText = "";
            this.txt_name_db.SelectionLength = 0;
            this.txt_name_db.SelectionStart = 0;
            this.txt_name_db.ShortcutsEnabled = true;
            this.txt_name_db.Size = new System.Drawing.Size(379, 30);
            this.txt_name_db.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_name_db.TabIndex = 4;
            this.txt_name_db.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_name_db.TextMarginBottom = 0;
            this.txt_name_db.TextMarginLeft = 3;
            this.txt_name_db.TextMarginTop = 1;
            this.txt_name_db.TextPlaceholder = "database";
            this.txt_name_db.UseSystemPasswordChar = false;
            this.txt_name_db.WordWrap = true;
            // 
            // txt_server
            // 
            this.txt_server.AcceptsReturn = false;
            this.txt_server.AcceptsTab = false;
            this.txt_server.AnimationSpeed = 200;
            this.txt_server.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_server.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_server.AutoSizeHeight = true;
            this.txt_server.BackColor = System.Drawing.Color.Transparent;
            this.txt_server.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_server.BackgroundImage")));
            this.txt_server.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_server.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_server.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_server.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_server.BorderRadius = 10;
            this.txt_server.BorderThickness = 1;
            this.txt_server.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_server.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_server.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_server.DefaultText = "";
            this.txt_server.FillColor = System.Drawing.Color.White;
            this.txt_server.HideSelection = true;
            this.txt_server.IconLeft = null;
            this.txt_server.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_server.IconPadding = 10;
            this.txt_server.IconRight = null;
            this.txt_server.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_server.Lines = new string[0];
            this.txt_server.Location = new System.Drawing.Point(34, 198);
            this.txt_server.MaxLength = 32767;
            this.txt_server.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_server.Modified = false;
            this.txt_server.Multiline = false;
            this.txt_server.Name = "txt_server";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_server.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_server.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_server.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_server.OnIdleState = stateProperties32;
            this.txt_server.Padding = new System.Windows.Forms.Padding(3);
            this.txt_server.PasswordChar = '\0';
            this.txt_server.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_server.PlaceholderText = "server";
            this.txt_server.ReadOnly = false;
            this.txt_server.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_server.SelectedText = "";
            this.txt_server.SelectionLength = 0;
            this.txt_server.SelectionStart = 0;
            this.txt_server.ShortcutsEnabled = true;
            this.txt_server.Size = new System.Drawing.Size(379, 30);
            this.txt_server.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_server.TabIndex = 2;
            this.txt_server.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_server.TextMarginBottom = 0;
            this.txt_server.TextMarginLeft = 3;
            this.txt_server.TextMarginTop = 1;
            this.txt_server.TextPlaceholder = "server";
            this.txt_server.UseSystemPasswordChar = false;
            this.txt_server.WordWrap = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::HELVETAS.Properties.Resources.database_settings;
            this.pictureBox1.Location = new System.Drawing.Point(177, 66);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(107, 108);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // disconnect_but
            // 
            this.disconnect_but.AllowAnimations = true;
            this.disconnect_but.AllowMouseEffects = true;
            this.disconnect_but.AllowToggling = false;
            this.disconnect_but.AnimationSpeed = 200;
            this.disconnect_but.AutoGenerateColors = false;
            this.disconnect_but.AutoRoundBorders = false;
            this.disconnect_but.AutoSizeLeftIcon = true;
            this.disconnect_but.AutoSizeRightIcon = true;
            this.disconnect_but.BackColor = System.Drawing.Color.Transparent;
            this.disconnect_but.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.disconnect_but.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("disconnect_but.BackgroundImage")));
            this.disconnect_but.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.disconnect_but.ButtonText = "disconnect";
            this.disconnect_but.ButtonTextMarginLeft = 0;
            this.disconnect_but.ColorContrastOnClick = 45;
            this.disconnect_but.ColorContrastOnHover = 45;
            this.disconnect_but.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.disconnect_but.CustomizableEdges = borderEdges6;
            this.disconnect_but.DialogResult = System.Windows.Forms.DialogResult.None;
            this.disconnect_but.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.disconnect_but.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.disconnect_but.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.disconnect_but.Enabled = false;
            this.disconnect_but.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.disconnect_but.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.disconnect_but.ForeColor = System.Drawing.Color.White;
            this.disconnect_but.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.disconnect_but.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.disconnect_but.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.disconnect_but.IconMarginLeft = 11;
            this.disconnect_but.IconPadding = 10;
            this.disconnect_but.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.disconnect_but.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.disconnect_but.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.disconnect_but.IconSize = 25;
            this.disconnect_but.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.disconnect_but.IdleBorderRadius = 20;
            this.disconnect_but.IdleBorderThickness = 1;
            this.disconnect_but.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.disconnect_but.IdleIconLeftImage = null;
            this.disconnect_but.IdleIconRightImage = null;
            this.disconnect_but.IndicateFocus = false;
            this.disconnect_but.Location = new System.Drawing.Point(296, 391);
            this.disconnect_but.Name = "disconnect_but";
            this.disconnect_but.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.disconnect_but.OnDisabledState.BorderRadius = 20;
            this.disconnect_but.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.disconnect_but.OnDisabledState.BorderThickness = 1;
            this.disconnect_but.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.disconnect_but.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.disconnect_but.OnDisabledState.IconLeftImage = null;
            this.disconnect_but.OnDisabledState.IconRightImage = null;
            this.disconnect_but.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.disconnect_but.onHoverState.BorderRadius = 20;
            this.disconnect_but.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.disconnect_but.onHoverState.BorderThickness = 1;
            this.disconnect_but.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.disconnect_but.onHoverState.ForeColor = System.Drawing.Color.White;
            this.disconnect_but.onHoverState.IconLeftImage = null;
            this.disconnect_but.onHoverState.IconRightImage = null;
            this.disconnect_but.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.disconnect_but.OnIdleState.BorderRadius = 20;
            this.disconnect_but.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.disconnect_but.OnIdleState.BorderThickness = 1;
            this.disconnect_but.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.disconnect_but.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.disconnect_but.OnIdleState.IconLeftImage = null;
            this.disconnect_but.OnIdleState.IconRightImage = null;
            this.disconnect_but.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.disconnect_but.OnPressedState.BorderRadius = 20;
            this.disconnect_but.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.disconnect_but.OnPressedState.BorderThickness = 1;
            this.disconnect_but.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.disconnect_but.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.disconnect_but.OnPressedState.IconLeftImage = null;
            this.disconnect_but.OnPressedState.IconRightImage = null;
            this.disconnect_but.Size = new System.Drawing.Size(125, 25);
            this.disconnect_but.TabIndex = 16;
            this.disconnect_but.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.disconnect_but.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.disconnect_but.TextMarginLeft = 0;
            this.disconnect_but.TextPadding = new System.Windows.Forms.Padding(0);
            this.disconnect_but.UseDefaultRadiusAndThickness = true;
            this.disconnect_but.Click += new System.EventHandler(this.disconnect_but_Click);
            // 
            // settibg_db
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ControlDark;
            this.ClientSize = new System.Drawing.Size(450, 519);
            this.Controls.Add(this.disconnect_but);
            this.Controls.Add(this.bunifuAppBar1);
            this.Controls.Add(this.connect_but);
            this.Controls.Add(this.bunifuButton24);
            this.Controls.Add(this.save_but);
            this.Controls.Add(this.test_connect_but);
            this.Controls.Add(this.txt_password);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txt_user);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txt_name_db);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.txt_server);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pictureBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "settibg_db";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "settibg_db";
            this.Load += new System.EventHandler(this.settibg_db_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_name_db;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txt_server;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txt_password;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 test_connect_but;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 save_but;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton24;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 connect_but;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.Utils.BunifuAppBar bunifuAppBar1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 disconnect_but;
    }
}